#!/usr/bin/env ruby

require 'optparse'
cwd = File.dirname(__FILE__)
require "./#{cwd}/lib/fetch.rb"

options = {:show_metadata => false}

OptionParser.new do |opts|
  opts.banner = "Usage: fetch <URI> [<URI> [...]]"

  opts.on('-m', '--metadata', 'show metadata') do |opt|
    options[:show_metadata] = opt
  end

  opts.on('-m', '--metadata', 'show metadata') do |opt|
    options[:show_metadata] = opt
  end
end.parse!

if options[:show_metadata]
  Fetcher.fetch_all_metadata(ARGV)
else
  Fetcher.fetch_all(ARGV)
end
