#!/usr/bin/env ruby

require 'optparse'
require './fetch.rb'

options = {}

OptionParser.new do |opts|
  opts.banner = "Usage: fetch <URI> [<URI> [...]]"
end.parse!

ARGV.each do |url|
  Fetcher.new(url).fetch
end
